site_name: Preview of Synergy Studio Developer Documentation
site_url: "https://ExtremeEventSolutions.github.io/ees-synergystudio-apis-staging/"
# site_url: "https://turbo-fortnight-v7e7no5.pages.github.io/"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: blue
      accent: deep orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue
      accent: deep purple
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
copyright: Copyright &copy; 2024 <a href="https://www.verisk.com/solutions/extreme-event-risk/" target="_blank" rel="noopener">Verisk Analytics</a>